import { ReactNode } from "react";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";

//import "@stream-io/video-react-sdk/dist/css/styles.css";
//import "react-datepicker/dist/react-datepicker.css";
//import "./globals.css";
//import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
        appearance={{
          layout: {
            logoImageUrl: '/icons/yoom-logo.svg', // Logo on the Signup-Signin Page
            socialButtonsVariant: 'iconButton'
          },
          variables: {
            colorText: "#fff",
            colorPrimary: "#0E78F9", // Button Color on Signup-Signin Page
            colorBackground: "#1c1f2e",
            colorInputBackground: '#252a41',
            colorInputText: '#fff',
          }
        }}
      >
      <body className={`${inter.className} bg-dark-2`}>
        {children}</body>
      </ClerkProvider>
    </html>
  );
}
